// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rn_transaction_system.Data;

#nullable disable

namespace rn_transaction_system.Migrations
{
    [DbContext(typeof(DbCon))]
    partial class DbConModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("rn_transaction_system.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1000m,
                            RowVersion = new byte[0],
                            UserId = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 2000m,
                            RowVersion = new byte[0],
                            UserId = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 3000m,
                            RowVersion = new byte[0],
                            UserId = "user3"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 4000m,
                            RowVersion = new byte[0],
                            UserId = "user4"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 5000m,
                            RowVersion = new byte[0],
                            UserId = "user5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
