version: '3.8'

services:
  rn_transaction_system:
    image: rn_transaction_system:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5105:5105"
      - "7141:7141"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7141;http://+:5105
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "fghfhdghd64jhfgj"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

